@base_url = http://localhost:8080/api

### ユーザー認証
POST {{ base_url }}/login/signIn HTTP/1.1
content-type: application/json

{
    "account": "admin",
    "password": "admin"
}

### ログアウト
POST {{ base_url }}/common/users/logout HTTP/1.1
content-type: application/json

### 認証済みか確認する
GET {{ base_url }}/common/app/isAuthorized HTTP/1.1
